name: kabod_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#last ios version: 1.0.23
version: 1.1.1+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers:
  cupertino_icons: ^1.0.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^1.0.6
  datetime_picker_formfield: ^2.0.0
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  firebase_messaging:
  firebase_storage: ^8.0.4
  flutter_colorpicker: ^0.3.4
  flutter_form_builder: ^6.0.0
  flutter_local_notifications: ^5.0.0+3
  flutter_staggered_animations: ^1.0.0
  flutter_keyboard_visibility_web: ^2.0.0
  flutter_native_timezone: ^1.0.10
  fluttertoast: ^8.0.6
  font_awesome_flutter: ^9.0.0
  http: ^0.13.1
  intl: ^0.17.0
  image_picker:
  image_cropper: ^1.4.0
  numberpicker: ^1.3.0
  photo_view: ^0.11.1
  provider: ^4.3.3
  random_string: ^2.1.0
  screen: ^0.0.5
  shared_preferences: ^2.0.5
  table_calendar: ^2.3.3
  url_launcher: ^6.0.4
  firebase_in_app_messaging: ^0.5.0+5
  quiver: ^3.0.1
  rxdart:
  package_info_plus: ^1.0.3
  device_info: ^2.0.2
  firebase_helpers:
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  camera: ^0.8.1+5
  file_picker: ^3.0.3
  permission_handler: ^8.1.3
  path_provider: ^2.0.2
  video_trimmer: ^0.5.4
  story_view: ^0.13.1
  video_player: ^2.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
  ios: true
  image_path_ios: "assets/images/app_icon.png"
flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/gif/

  fonts:
  - family: Nunito
    fonts:
    - asset: assets/fonts/Nunito-Bold.ttf
flutter_intl:
  enabled: false
  main_locale: en
#  class_name:
